### ISSUE TITLE
medbook.io deploy needs to not use docker-compose-dev.yml file

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook#1]
Right now ( develop commit 85a5936 ) the docker-compose-dev.yml file is customized for the medbook.io deploy , for which mongo is running on a separate box.
This means it doesn't work out-of-the-box when cloned on a dev box.

The build running on medbook.io needs to be dockerized and docker-compose.yml updated to match the versions so that docker-compose-dev can be used for dev box config, as appropriate.

I suggest making a ./startProd.sh to parallel startDev.sh ; this would consist of, eg

`docker-compose up`

**Comment by mokolodi1** [comment]
@rissem : the deploy wasn't working with the built version of gateway, so I'm running all the apps from CI built docker images except gateway. I haven't looked into it, but I will when you come down on Wednesday.
