### ISSUE TITLE
Change background color of site (or otherwise visually disambiguate) when running on staging

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook#13]
Detect when medbook is running in a non-production environment and visually mark this in some obvious fashion.  For example, the background color could be set to pale yellow. (Or any other change simple to implement & visible on every page.)

Rationale: Currently many links go directly to medbook.io regardless of environment & it is very easy to accidentally perform a task on prod that was intended for staging.

**Comment by mokolodi1** [comment]
On master branch on both patient-care and wrangler. It'll be in the next release of MedBook.

**Comment by mokolodi1** [comment]
One quick thing to note is that the code I've reference in the above to commits should be in a package, but I don't want to refactor that until we have MedBook_ up and running.
