### ISSUE TITLE
Delete old backups to save space

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook#7]
backups.medbook.io has a `/backups` drive that has 500gb. Currently each backup takes 4.5 gb so it's only a matter of time before that disk fills up.

**Comment by e-t-k** [comment]
How frequently do backups run?

**Comment by mokolodi1** [comment]
Every night at 3:30 am

**Comment by e-t-k** [comment]
The backup process is documented in the script itself, https://github.com/UCSC-MedBook/MedBook/blob/master/scripts/create_backup.sh , which is running as a cron job on prod. We access backups.medbook.io via prod.
