### ISSUE TITLE
Move backup location

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook#8]
the process of backing up takes up too much drive space. mount a new drive on prod and change so that it is backed up to that instead.

**Comment by rcurrie** [comment]
To keep the load down on production and reduce network I/O I propose we rsync everything to backup before tar - that way only incremental blob store is backed up. Then on backup.medbook.io we could periodically tar up complete backup. Most of the time the rsync will only be coping changed files and the mongo dump (and 'might' send a diff of it, not sure)

**Comment by mokolodi1** [comment]
We could also give the backup box access to the mongo db directly. For now I've attached a disk to prod and backups happen there.
